### ISSUE TITLE
ConsumeFuzzer.GetBytes cannot generate long byte slices

### ISSUE THREAD

**Issue by elias-orijtech** [AdaLogics/go-fuzz-headers#67]
As per https://github.com/AdaLogics/go-fuzz-headers/blob/f1761e18c0c6d721973fbe338aa87dcd60e11c41/consumer.go#L422 a slice length is encoded in a single byte, making slices longer than 255 impossible to generate. See also https://github.com/google/oss-fuzz/issues/7600.

**Comment by AdamKorcz** [comment]
This has been fixed with https://github.com/AdaLogics/go-fuzz-headers/pull/85.

Thank you for raising the issue.
