### ISSUE TITLE
Error "Created too large a string"

### ISSUE THREAD

**Issue by zhlu32** [AdaLogics/go-fuzz-headers#97]
func TestValidateProject(t *testing.T) {
	data := []byte{'R', 'a', 'n', 'd', 'o', 'm'}
	f := fuzz.NewConsumer(data)
	str, _ := f.GetString()
	fmt.Println(str)
}

The above code run ERROR, debug show below:

![image](https://user-images.githubusercontent.com/3273178/199438815-d3b9c798-1d49-45ac-949b-d2c70ee3882e.png)

The lib version:
go-fuzz-headers@v0.0.0-20221007124625-37f5449ff7df

Go version:
go1.8

**Comment by AdamKorcz** [comment]
Hello, yes, this is correct. To mitigate, instead of doing this:

```go
str, _ := f.GetString()
fmt.Println(str)
}
```

... catch the error:
```go 
str, err := f.GetString()
if err != nil {
    return
}
fmt.Println(str)
}
```
